/* ─────────────────────────────────────────────────────────────────────────────
   aboutData.js — Southern Province Planning Secretariat
   Central data source for all About pages (topics + officials).
───────────────────────────────────────────────────────────────────────────── */

/* ── Topic pages ─────────────────────────────────────────────────────────── */
export const ABOUT_TOPICS = [
  {
    id: 'overview',
    path: '/about/overview',
    label: 'Planning Secretariat Overview',
    labelSi: 'සැලසුම් ලේකම් කාර්යාල දළ විශ්ලේෂණය',
    labelTa: 'திட்டமிடல் செயலாலய கண்ணோட்டம்',
    heroTitle: 'Planning Secretariat Overview',
    heroSub: 'Vision, mission, and the institutional mandate of the Southern Province Planning Secretariat.',
    icon: 'overview',
  },
  {
    id: 'organization-structure',
    path: '/about/organization-structure',
    label: 'Organization Structure',
    labelSi: 'සංවිධාන ව්‍යූහය',
    labelTa: 'நிறுவன அமைப்பு',
    heroTitle: 'Organization Structure',
    heroSub: 'The hierarchical framework and administrative units of the Secretariat.',
    icon: 'structure',
  },
  {
    id: 'functions-duties',
    path: '/about/functions-duties',
    label: 'Functions & Duties',
    labelSi: 'කාර්ය සාධන හා යුතුකම්',
    labelTa: 'செயல்பாடுகள் மற்றும் கடமைகள்',
    heroTitle: 'Functions & Duties',
    heroSub: 'Statutory responsibilities and core functions entrusted to the Secretariat.',
    icon: 'functions',
  },
  {
    id: 'history',
    path: '/about/history',
    label: 'History',
    labelSi: 'ඉතිහාසය',
    labelTa: 'வரலாறு',
    heroTitle: 'Our History',
    heroSub: 'A chronicle of institutional milestones and development of the Planning Secretariat.',
    icon: 'history',
  },
]

/* ── Key Officials ───────────────────────────────────────────────────────── */
export const KEY_OFFICIALS = [
  {
    id: 'deputy-secretary-planning',
    path: '/about/deputy-secretary-planning',
    label: 'Deputy Chief Secretary – Planning',
    labelSi: 'නියෝජ්‍ය ප්‍රධාන ලේකම් – සැලසුම්',
    labelTa: 'துணை தலைமை செயலர் – திட்டமிடல்',
    nameSi: 'එම්.කේ.ජී.එස්.පී.කේ. ජයසේකර මහතා',
    nameTa: 'திரு எம்.கே.ஜி.எஸ்.பி.கே. ஜயசேகர',
    positionSi: 'නියෝජ්‍ය ප්‍රධාන ලේකම් – සැලසුම්',
    positionTa: 'துணை தலைமை செயலர் – திட்டமிடல்',
    name: 'Mr. M.K.G.S.P.K. Jayasekara',
    position: 'Deputy Chief Secretary – Planning',
    department: 'Planning Secretariat, Southern Province',
    positionRank: 'Senior Executive',
    photo: '/branding/sec-prof.png',
    heroTitle: 'Deputy Chief Secretary – Planning',
    heroSub: 'Senior executive officer responsible for strategic planning oversight.',
    icon: 'deputy-sec',
    responsibilities: [
      'Strategic planning oversight and information for the provincial policy formulation endeavors.',
      'Coordination with provincial and national level planning bodies to delivering an effectful and Results oriented Development Planning Approach.',
      'Administrative supervision of all planning divisions in the provincial setups.',
      'Budget planning, resource allocation and financial oversight of all department endeavors of the Southern Provincial Council.',
      'Monitoring and evaluation of provincial development projects.',
      'Liaison with Finance Commission and Relevant central government agencies.',
      'Representing the Secretariat at official inter-agency Discussions.',
    ],
    contact: {
      phone: '+94 91 450 0656',
      email: 'spdcsp@gmail.com',
      office: 'Southern Province Planning Secretariat, Galle',
    },
  },
  {
    id: 'director-planning',
    path: '/about/director-planning',
    label: 'Director – Planning',
    labelSi: 'අධ්‍යක්ෂ – සැලසුම්',
    labelTa: 'இயக்குநர் – திட்டமிடல்',
    name: 'Mrs. K.S.S. Weerawardhane',
    position: 'Director – Planning',
    positionRank: 'Director Grade',
    photo: '/branding/dir.png',
    heroTitle: 'Director – Planning',
    heroSub: 'Director responsible for executing provincial planning programmes.',
    icon: 'director',
    responsibilities: [
      {
        text: 'Planning, Development and Monitoring',
        subItems: [
          'Assist in the implementation of development and social welfare programmes at the Divisional Secretariat and Grama Niladhari Division levels.',
          'Coordinate and facilitate the implementation of development and social welfare programmes at the Divisional Secretariat level through relevant government institutions, community organizations, and other stakeholders.',
          'Assist in the implementation, follow-up, monitoring, and evaluation of poverty alleviation and development programmes.',
          'Conduct surveys and maintain related records.',
          'Facilitate the implementation of social welfare programmes and maintain coordination with beneficiary groups and relevant institutions.',
          'Maintain and update beneficiary information through the relevant software system (MS Software), prepare reports, and perform other related duties as assigned.',
        ],
      },
      {
        text: 'Community Participation and Empowerment',
        subItems: [
          'Assist in organizing and conducting awareness programmes at the community level.',
          'Facilitate community participation in development activities and maintain records related to community-based organizations and welfare programmes.',
          'Assist in identifying community needs and issues.',
          'Maintain relevant documentation and reports.',
          'Assist in coordinating with government and non-government organizations engaged in development and welfare activities at the Divisional Secretariat level.',
          'Perform any other duties assigned by the Divisional Secretary or other authorized officers in relation to social welfare, development, poverty alleviation, and community empowerment programmes.',
        ],
      },
    ],
    contact: {
      phone: '+94 91 222 3868',
      email: 'spdcsp@gmail.com',
      office: 'Southern Province Planning Secretariat, Galle',
    },
  },
]

/* ── Deputy Directors ────────────────────────────────────────────────────── */
export const DEPUTY_DIRECTORS = [
  {
    id: '1',
    path: '/about/deputy-directors/1',
    label: 'Deputy Director I',
    name: 'Mrs. M.A.K.N. Gunawardana',
    position: 'Deputy Director – Planning',
    positionNumber: 'I',
    department: 'Planning Division – I',
    photo: '/branding/ddsp1.png',
    heroTitle: 'Deputy Director – Planning',
    heroSub: 'Deputy Director of the Southern Province Planning Secretariat.',
    responsibilities: [
      'Coordination of planning activities in assigned district',
      'Preparation of divisional planning reports',
      'Field supervision of development projects',
      'Data collection and statistical analysis',
      'Liaison with local government authorities',
    ],
    contact: {
      phone: '+94 91 222 XXXX',
      email: 'spdcsp@gmail.com',
      office: 'Planning Division I, Southern Province',
    },
  },
  {
    id: '2',
    path: '/about/deputy-directors/2',
    label: 'Deputy Director II',
    name: 'Mrs. Chandrika Malepathirana',
    position: 'Deputy Director – Planning',
    positionNumber: 'II',
    department: 'Planning Division – II',
    photo: '/branding/ddsp2.png',
    heroTitle: 'Deputy Director – Planning',
    heroSub: 'Deputy Director of the Southern Province Planning Secretariat.',
    responsibilities: [
      {
        text: 'Planning and coordinating development initiatives in the following ministry and relevant sectors:',
        subItems: [
          'Education Ministry',
          'Education Department',
          'Southern Province Road Development Authority',
          'Land and Land Development Authority',
          'School Nutrition Programme',
          'Rural Bridges Development',
          'Clean Sri Lanka Programme of Education Sector',
        ],
      },
      'Monitoring of the annual development plan in the above sectors',
      'Reporting, reviewing and referring progress of the annual development plan to the relevant institutions',
    ],
    contact: {
      phone: '0912227882',
      email: 'spdcsp@gmail.com',
      office: 'Planning Secretariat, Southern Province',
    },
  },
  {
    id: '3',
    path: '/about/deputy-directors/3',
    label: 'Deputy Director III',
    name: 'Mrs. N.C. Dissanayake',
    position: 'Deputy Director – Planning',
    positionNumber: 'III',
    department: 'Planning Division – III',
    photo: '/branding/ddsp3.png',
    heroTitle: 'Deputy Director – Planning',
    heroSub: 'Deputy Director of the Southern Province Planning Secretariat.',
    responsibilities: [
      'Planning and coordinating Agriculture sector development initiatives in the province',
      'Facilitating implementation and monitoring of Agriculture sector projects',
      'Managing Provincial Climate Unit activities effectively',
      'Coordinating Provincial Adaptation Plan implementation activities',
      'Field supervision of development projects',
    ],
    contact: {
      phone: '0912231197',
      email: 'spdcsp@gmail.com',
      office: 'Planning Secretariat, Southern Province',
    },
  },
  {
    id: '4',
    path: '/about/deputy-directors/4',
    label: 'Deputy Director IV',
    name: 'Mrs. H.I.H. Salgamuwa',
    position: 'Deputy Director – Planning',
    positionNumber: 'IV',
    department: 'Planning Division – IV',
    photo: '/branding/ddsp4.png',
    heroTitle: 'Deputy Director – Planning',
    heroSub: 'Deputy Director of the Southern Province Planning Secretariat.',
    responsibilities: [
      {
        text: 'Planning and controlling development initiatives in the following sectors in the province:',
        subItems: [
          'Inland Fisheries',
          'Estate Infrastructure',
          'Rural Electrification',
          'Livestock',
          'Environment',
          'Small Industries',
        ],
      },
      'Monitoring of the annual development plan relevant to the above sectors',
      'Reporting progress of the annual development plan',
    ],
    contact: {
      phone: '0912248750',
      email: 'spdcsp@gmail.com',
      office: 'Planning Secretariat, Southern Province',
    },
  },
  {
    id: '5',
    path: '/about/deputy-directors/5',
    label: 'Deputy Director V',
    name: 'Mrs. A.K.E. Madusarani',
    position: 'Deputy Director – Planning',
    positionNumber: 'V',
    department: 'Planning Division – V',
    photo: '/branding/ddsp5.png',
    heroTitle: 'Deputy Director – Planning',
    heroSub: 'Deputy Director of the Southern Province Planning Secretariat.',
    responsibilities: [
      'Coordination of planning and monitoring implementation activities in Southern Province Chief Ministry',
      'Preparation of provincial annual development estimate and plans for PSDG and CBG',
      'Coordination of the Provincial Planning Committee',
      'Coordination and fund allocation for Special Grants, Flexible Grants, and related grants',
      'Field supervision of development projects under Chief Ministry, Special and Flexible Grants',
      'Preparation of the annual weightages for PSDG sectors and coordination of Budget Allocations',
    ],
    contact: {
      phone: '+94 91 223 1943',
      email: 'spdcsp@gmail.com',
      office: 'Planning Secretariat, Southern Province',
    },
  },
  {
    id: '6',
    path: '/about/deputy-directors/6',
    label: 'Deputy Director VI',
    name: 'Mrs. A.D.S. Priyadarshani',
    position: 'Deputy Director – Planning',
    positionNumber: 'VI',
    department: 'Planning Division – VI',
    photo: '/branding/ddsp6.png',
    heroTitle: 'Deputy Director – Planning',
    heroSub: 'Deputy Director of the Southern Province Planning Secretariat.',
    responsibilities: [
      {
        text: 'Planning and coordinating the following sectors\' development initiatives in the province:',
        subItems: [
          'Sports',
          'Rural Development',
          'Social Welfare',
          'Cultural and Art Affairs',
          'Probation and Child Care Services',
          'Housing and Construction',
          'Youth Affairs',
          'Women\'s Affairs',
          'Manpower and Employment',
          'Home Economy Enhancement',
        ],
      },
      'Monitoring of the annual development plan relevant to the above sectors',
      'Field supervision of development projects',
    ],
    contact: {
      phone: '0912248750',
      email: 'spdcsp@gmail.com',
      office: 'Planning Secretariat, Southern Province',
    },
  },
]

/* ── All quick links combined (used in sidebar) ─────────────────────────── */
export const ALL_QUICK_LINKS = [
  { group: 'About', items: ABOUT_TOPICS },
  {
    group: 'Key Officials',
    items: [
      ...KEY_OFFICIALS,
      {
        id: 'deputy-directors',
        path: '/about/deputy-directors',
        label: 'Deputy Directors',
        labelSi: 'නියෝජ්‍ය අධ්‍යක්ෂවරු',
        labelTa: 'துணை இயக்குநர்கள்',
        heroTitle: 'Deputy Directors',
        heroSub: 'Planning team deputy directors of the Southern Province Planning Secretariat.',
        icon: 'team',
      },
    ],
  },
]
